---

### Generic smell configuration

detectors:
  # You can disable smells completely
  IrresponsibleModule:
    enabled: false
  TooManyStatements:
    enabled: false
  DuplicateMethodCall:
    max_calls: 2


### Excluding directories

# Directories and files below will not be scanned at all
exclude_paths:
  - db/migrate