require:
  - rubocop-rails

AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'test/**/*'
    - 'db/schema.rb'
    - 'bin/*'
    - 'db/**/*.rb'
    - 'config/**/*.rb'
    - 'spec/**/*.rb'
    - 'lib/tasks/**/*'
  NewCops: enable
  TargetRubyVersion: 2.7.2


Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Layout/LineLength:
  Enabled: false
  Max: 180
  IgnoredPatterns: ['\A#']

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - 'app/dashboards/**/*.rb'
  